### ISSUE TITLE
Failed building wheel for pypandoc

### ISSUE THREAD

**Issue by sebastianst** [ethereum/eth2.0-deposit-cli#193]
I followed option 2 to build deposit-cli with native Python and when running `pip3 install -r requirements.txt` I get the following error
```
Requirement already satisfied: click==7.1.2 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 40)) (7.1.2)
Requirement already satisfied: six==1.15.0 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 69)) (1.15.0)
Requirement already satisfied: cached-property==1.5.2 in /usr/lib/python3.9/site-packages (from -r requirements.txt (line 72)) (1.5.2)
Collecting cytoolz==0.10.1
  Downloading cytoolz-0.10.1.tar.gz (475 kB)
     |████████████████████████████████| 475 kB 26.1 MB/s 
Collecting eth-hash==0.2.0
  Downloading eth-hash-0.2.0.tar.gz (6.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-586xffq7/eth-hash_020bb57e28a44f19bbc4d3e79e0bc476/setup.py'"'"'; __file__='"'"'/tmp/pip-install-586xffq7/eth-hash_020bb57e28a44f19bbc4d3e79e0bc476/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yjcmt6lh
         cwd: /tmp/pip-install-586xffq7/eth-hash_020bb57e28a44f19bbc4d3e79e0bc476/
    Complete output (47 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-owzcy7da/pypandoc_c852620a913c4fe2ba30d4ba9e324535/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-owzcy7da/pypandoc_c852620a913c4fe2ba30d4ba9e324535/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3yyqv2s3
           cwd: /tmp/pip-wheel-owzcy7da/pypandoc_c852620a913c4fe2ba30d4ba9e324535/
      Complete output (8 lines):
      no pandoc found, building platform unspecific wheel...
      use 'python setup.py download_pandoc' to download pandoc.
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for pypandoc
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp4s796e19', '--quiet', 'pypandoc']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-586xffq7/eth-hash_020bb57e28a44f19bbc4d3e79e0bc476/setup.py", line 44, in <module>
        setup(
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/usr/lib/python3.9/site-packages/setuptools/dist.py", line 780, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp4s796e19', '--quiet', 'pypandoc']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

`python -V`: `3.9.2`
System: Arch Linux

**Comment by sebastianst** [comment]
When following option 3 (virtualenv), I get
```
% pip3 install -r requirements.txt
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```
Note that the instructions say to call `python3 setup.py install` before `pip3 install`, which works. Option 2 goes the other way round.

**Comment by sebastianst** [comment]
So the problem seems to be a missing installation of `pandoc`. It's not mentioned in the build requirements and I'd like to avoid installing pandoc with all its Haskell dependencies on my machine. Would be great if the building of docs could be somehow disabled optionally.

**Comment by hwwhww** [comment]
Hi @sebastianst,

Hmm, I couldn't reproduce your error from my side.
What's your pip version? You can get it from `pip3 --version`. If it's too old, try `python3 -m pip install --upgrade pip`.

**Comment by sebastianst** [comment]
`pip 20.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)` - on Arch, I usually only have problems because stuff is too _new_ :sweat_smile:

Anyway, the main problem seems to be a missing installation of `pandoc`

**Comment by samael0119** [comment]
pip install pypandoc
